pipelines:
  - name: check
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
    success:
      gerrit:
        verified: 1
    failure:
     gerrit:
        verified: -1

jobs:
  - name: ^.*-merge$
    failure-message: Unable to merge change, please rebase and try again.

projects:
  - name: definitions
    check:
      - build:
        - build_test:
          - artifact_upload
